@startwbs
'https://plantuml.com/mindmap-diagram

skinparam tabSize 4

+ To fix
 + Scene editor
  + Collapsible styling
   + Create tree lines
    + Create sub-input components with type diffs
   + Top-level display no-line [rep array]
   + Addition buttons instance collection components, map to hot-reload
   + Async load on open, deload on close, to save performance
  + Clear present on save data in editor
  + Display popup upon closing unsaved
   + Save writes data to chrome, editing hot-reload engine
    + Stringify to JSON
  + Map tree to engine
   + Create generic system for mapping to types/tree



@endwbs
